# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Autotools on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)

jobs:
 build-qt5:
    name: Ubuntu Build Qt5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libjack-dev libasound2-dev qtbase5-dev  qttools5-dev-tools liblo-dev lv2-dev libpango1.0-dev libcairo2-dev libpugl-dev
      - name: Configure with autotools
        run: |
          autoreconf -i
          ./configure --enable-qt5
      - name: Build project
        run: make -j4

 build-qt6:
    name: Ubuntu Build Qt6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libjack-dev libasound2-dev qt6-base-dev  qt6-tools-dev qt6-l10n-tools liblo-dev lv2-dev libpango1.0-dev libcairo2-dev libpugl-dev
      - name: Configure with autotools
        run: |
          autoreconf -i
          ./configure
      - name: Build project
        run: make -j4

